# Pydantic Models - Request/Response Validation
# Validates data entering and leaving the API
from pydantic import BaseModel
from datetime import datetime
from typing import Optional, List

# ============================================================================
# ACCOUNT SCHEMAS
# ============================================================================

class AccountBase(BaseModel):
    # Base account data - shared between create and response. These are the core fields every account has.
    business_name: str
    owner_name: str
    industry: str
    status: str = "active"

class AccountCreate(AccountBase):
    # Schema for creating a new account.
    # Client sends this when: POST /accounts
    #Why separate from AccountBase- Create doesn't need id (auto-generated by database)and Create doesn't need timestamps (auto-generated)
    pass


class AccountUpdate(BaseModel):
    """
    Schema for updating an account.
    Client sends this when: PUT /accounts/{id}
    
    Why Optional:
    - Client might only update business_name, not industry
    - All fields are optional (update what you need)
    """
    business_name: Optional[str] = None
    status: Optional[str] = None
    lifecycle_stage: Optional[str] = None


class AccountResponse(AccountBase):
    """
    Schema for API response when returning an account.
    API sends this when: GET /accounts/{id}
    
    Why different from AccountCreate:
    - Includes id, timestamps, calculated fields
    - Client receives read-only info (churn_risk_score, days_since_open)
    """
    id: int
    account_id: str
    opening_date: datetime
    lifecycle_stage: str
    days_since_open: int
    churn_risk_score: float
    monthly_turnover: Optional[float] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True  # Allow reading from SQLAlchemy models


# ============================================================================
# POS TRANSACTION SCHEMAS
# ============================================================================

class POSTransactionBase(BaseModel):
    """Base POS transaction data."""
    amount: float
    transaction_type: str  # "airtime", "electricity", "voucher"
    description: str
    merchant: str
    payment_method: Optional[str] = None  # tap_to_pay, scan_to_pay, card_swipe, mobile_wallet
    card_type: Optional[str] = None  # debit, credit


class POSTransactionCreate(POSTransactionBase):
    """
    Schema for recording a new POS transaction.
    Client sends: POST /transactions/pos
    """
    account_id: str


class POSTransactionResponse(POSTransactionBase):
    """
    Schema for API response with transaction details.
    API sends: GET /transactions/{id}
    """
    id: int
    account_id: str
    transaction_id: str
    transaction_date: datetime
    created_at: datetime

    class Config:
        from_attributes = True


# ============================================================================
# INSURANCE POLICY SCHEMAS
# ============================================================================

class InsurancePolicyBase(BaseModel):
    """Base insurance policy data."""
    policy_type: str
    status: str = "pending"


class InsurancePolicyCreate(InsurancePolicyBase):
    """
    Schema for creating insurance policy.
    Client sends: POST /policies/insurance
    """
    account_id: str


class InsurancePolicyResponse(InsurancePolicyBase):
    """
    Schema for API response with policy details.
    API sends: GET /policies/{id}
    """
    id: int
    account_id: str
    policy_id: str
    application_date: datetime
    activation_date: Optional[datetime] = None

    class Config:
        from_attributes = True

class InsurancePolicyUpdate(BaseModel):
    """Schema for updating an insurance policy."""
    policy_type: Optional[str] = None
    status: Optional[str] = None


# ============================================================================
# LOAN SCHEMAS
# ============================================================================

class LoanBase(BaseModel):
    """Base loan data."""
    amount: float
    status: str = "applied"
    loan_term: Optional[str] = None  # short_term, medium_term, long_term
    term_months: Optional[int] = None


class LoanCreate(LoanBase):
    """
    Schema for applying for a loan.
    Client sends: POST /loans
    """
    account_id: str


class LoanResponse(LoanBase):
    """
    Schema for API response with loan details.
    API sends: GET /loans/{id}
    """
    id: int
    account_id: str
    loan_id: str
    application_date: datetime
    approval_date: Optional[datetime] = None
    disbursement_date: Optional[datetime] = None

    class Config:
        from_attributes = True

class LoanUpdate(BaseModel):
    """
    Schema for updating a loan.
    Client sends this when: PUT /api/loans/{loan_id}
    """
    amount: Optional[float] = None  # Modify loan amount
    status: Optional[str] = None  # Update status
    qualified: Optional[bool] = None  # Add this: qualified or not
    loan_term: Optional[str] = None
    term_months: Optional[int] = None


# ============================================================================
# OTHER INCOME SCHEMAS
# ============================================================================

class OtherIncomeResponse(BaseModel):
    """
    Schema for API response with non-POS income (EFT received, cash
    deposits) - the revenue POSTransaction alone can't represent for
    accounts paid by invoice/bank transfer rather than card-present sale.
    """
    id: int
    account_id: str
    income_id: str
    income_type: str  # "eft_received", "cash_deposit"
    amount: float
    income_date: datetime

    class Config:
        from_attributes = True


# ============================================================================
# WEEKLY ACTIVE USER SCHEMAS
# ============================================================================

class WAUResponse(BaseModel):
    """
    Schema for returning Weekly Active User data.
    API sends: GET /accounts/{id}/wau
    """
    id: int
    account_id: str
    week_number: int
    usage_count: int
    is_active: bool
    services_used: List[str]
    most_used_service: Optional[str] = None
    adoption_rate: float
    
    class Config:
        from_attributes = True


# ============================================================================
# MONTHLY ACTIVE USER SCHEMAS
# ============================================================================

class MAUResponse(BaseModel):
    """
    Schema for returning Monthly Active User data.
    API sends: GET /accounts/{id}/mau
    """
    id: int
    account_id: str
    month: str
    usage_count: int
    is_active: bool
    services_used: List[str]
    peak_usage_day: Optional[str] = None
    peak_usage_time: Optional[str] = None
    adoption_rate: float
    
    class Config:
        from_attributes = True


# ============================================================================
# ANALYTICS SCHEMAS
# ============================================================================

class IndustryStats(BaseModel):
    """
    Schema for industry-level analytics.
    API sends: GET /analytics/by-industry
    """
    industry: str
    total_accounts: int
    active_accounts: int
    avg_churn_risk: float
    avg_adoption_rate: float


class AccountStats(BaseModel):
    """
    Schema for account-level statistics.
    API sends: GET /accounts/{id}/stats
    """
    account_id: str
    business_name: str
    lifecycle_stage: str
    wau_count: int
    mau_count: int
    total_pos_transactions: int
    insurance_policies: int
    loans: int
    churn_risk_score: float


# ============================================================================
# ERROR RESPONSE SCHEMA
# ============================================================================

class ErrorResponse(BaseModel):
    """
    Schema for error responses.
    API sends when something goes wrong.
    """
    detail: str
    error_code: str